services:
  laravel-app-kafka:
    image: bitnami/kafka:latest
    container_name: laravel-app-kafka
    restart: always
    ports:
      - "9092:9092" 
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    # entrypoint: [
    #   "sh", 
    #   "-c", 
    #   "sleep 5 && \ # Chờ 5 giây để Kafka khởi động
    #   kafka-topics.sh --create --topic thanh_toan_ve_thanh_cong --bootstrap-server laravel-app-kafka:9092 --replication-factor 1 --partitions 1 && \
    #   kafka-topics.sh --create --topic dat_ve_thanh_cong --bootstrap-server laravel-app-kafka:9092 --replication-factor 1 --partitions 1 && \
    #   tail -f /dev/null"
    # ]
    depends_on:
      - zookeeper
    networks:
      - backend
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "9093:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=laravel-app-kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - laravel-app-kafka
      - zookeeper
    networks:
      - backend
  laravel-app-redis:
    image: redis:latest
    container_name: laravel-app-redis
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redis-data:/data
    networks:
      - backend
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:laravel-app-redis:6379
    depends_on:
      - laravel-app-redis
    networks:
      - backend
  laravel-app-db:
    image: mysql:latest
    container_name: laravel-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456@
      MYSQL_DATABASE: diag_livecode
      MYSQL_USER: diag
      MYSQL_PASSWORD: 987654@
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  nginx:
    image: nginx:latest
    container_name: laravel-app-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./laravel/public:/var/www/html/laravel/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - frontend
      - backend
  laravel-app:
    container_name: laravel-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    extra_hosts:
      - "localhost:127.0.0.1"
    depends_on:
      - laravel-app-db
      - laravel-app-kafka
    networks:
      - backend
volumes:
  redis-data:
  mysql-data:
networks:
  frontend:
  backend: